---
- name: L2TP | Install xl2tpd
  ansible.builtin.apt:
    name: xl2tpd
    state: latest
    update_cache: true
  become: true

- name: L2TP | Copy xl2tpd-config files to hosts
  ansible.builtin.template:
    src: "xl2tpd.conf.j2"
    dest: "/etc/xl2tpd/xl2tpd.conf"
    owner: root
    mode: 0644
  become: true

- name: L2TP | Copy ppp-config files
  ansible.builtin.copy:
    src: "options.xl2tpd"
    dest: "/etc/ppp/options.xl2tpd"
    owner: root
    mode: 0644
  become: true

- name: L2TP | Copy chap-secrets files to hosts
  ansible.builtin.template:
    src: "chap-secrets.j2"
    dest: "/etc/ppp/chap-secrets"
    owner: root
    mode: 0644
  become: true

- name: L2TP | Run xl2tpd
  ansible.builtin.systemd:
    name: xl2tpd
    enabled: true
    state: started
    daemon_reload: true
  become: true
